// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLRepo creates a new instance of MockURLRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepo {
	mock := &MockURLRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLRepo is an autogenerated mock type for the URLRepo type
type MockURLRepo struct {
	mock.Mock
}

type MockURLRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepo) EXPECT() *MockURLRepo_Expecter {
	return &MockURLRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockURLRepo
func (_mock *MockURLRepo) Create(ctx context.Context, longURL string, alias string) (string, error) {
	ret := _mock.Called(ctx, longURL, alias)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, longURL, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, longURL, alias)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, longURL, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockURLRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - longURL string
//   - alias string
func (_e *MockURLRepo_Expecter) Create(ctx interface{}, longURL interface{}, alias interface{}) *MockURLRepo_Create_Call {
	return &MockURLRepo_Create_Call{Call: _e.mock.On("Create", ctx, longURL, alias)}
}

func (_c *MockURLRepo_Create_Call) Run(run func(ctx context.Context, longURL string, alias string)) *MockURLRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockURLRepo_Create_Call) Return(s string, err error) *MockURLRepo_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLRepo_Create_Call) RunAndReturn(run func(ctx context.Context, longURL string, alias string) (string, error)) *MockURLRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// SelectByAlias provides a mock function for the type MockURLRepo
func (_mock *MockURLRepo) SelectByAlias(ctx context.Context, alias string) (string, error) {
	ret := _mock.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for SelectByAlias")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepo_SelectByAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectByAlias'
type MockURLRepo_SelectByAlias_Call struct {
	*mock.Call
}

// SelectByAlias is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockURLRepo_Expecter) SelectByAlias(ctx interface{}, alias interface{}) *MockURLRepo_SelectByAlias_Call {
	return &MockURLRepo_SelectByAlias_Call{Call: _e.mock.On("SelectByAlias", ctx, alias)}
}

func (_c *MockURLRepo_SelectByAlias_Call) Run(run func(ctx context.Context, alias string)) *MockURLRepo_SelectByAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepo_SelectByAlias_Call) Return(s string, err error) *MockURLRepo_SelectByAlias_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLRepo_SelectByAlias_Call) RunAndReturn(run func(ctx context.Context, alias string) (string, error)) *MockURLRepo_SelectByAlias_Call {
	_c.Call.Return(run)
	return _c
}
