version: "2"
linters:
  default: none
  enable:
    # Correctness (критичные)
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused

    # Security
    - gosec

    # Performance
    - copyloopvar
    - noctx
    - perfsprint
    - prealloc

    # Code quality
    - gocyclo
    - funlen
    - goconst
    - gocritic
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - usestdlibvars

    # Style (минимум)
    - goprintffuncname
    - nolintlint
    - whitespace

  settings:
    funlen:
      lines: 150
      statements: 80
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          disabled: true
    nolintlint:
      require-explanation: true
      require-specific: true
    gosec:
      excludes:
        - G404 # weak random - если не crypto
