all: true
recursive: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName}}.go"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
template: testify
log-level: info

packages:
  github.com/hisshihi/url-shortener/core/repository:
    config:
      all: true