services:
  pg:
    image: postgres:18.3-alpine3.23
    restart: unless-stopped
    environment:
      POSTGRES_DB: url_short
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: